version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: portfolio-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb+srv://imdeepmind:8qLIJK6fPNwqvDzT@imdeepmind.9dwtmat.mongodb.net/?appName=Imdeepmind
      - NEXTAUTH_SECRET=development_secret_only
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: portfolio-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
